include:
- template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - scan
  # - deploy

docker_build:
  stage: build
  services:
    - name: docker:dind
      command: ["dockerd", "--host=tcp://0.0.0.0:2375"]
      alias: 'docker'
  image: registry.gitlab.com/coinsmaster/common/containers/docker-buildx:master
  before_script:
    - mkdir -p ~/.docker
    - echo "{\"auths\":{\"$DOCKER_REGISTRY\":{\"username\":\"$DOCKER_REGISTRY_USER\",\"password\":\"$DOCKER_REGISTRY_PASSWORD\"}}}" > ~/.docker/config.json
    - docker buildx create --driver=docker-container --name=buildkit-builder --use
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  script: |
      docker buildx build \
            --platform linux/arm/v7,linux/arm64/v8,linux/amd64 \
            --tag $CI_REGISTRY_IMAGE:latest \
            --tag $CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA} \
            --tag $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME} \
            --push \
            ${DOCKERFILE_DIR:- .}

  variables:
    DOCKER_REGISTRY_USER: $CI_REGISTRY_USER
    DOCKER_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
    DOCKER_REGISTRY: $CI_REGISTRY
    DOCKERFILE_DIR: $CI_PROJECT_DIR/container/


sast:
  stage: scan
kube_deploy:
  stage: deploy
  script:
    - echo "Deploy to test cluster"
  environment:
    name: gcp
    url: https://test.my-cloud.me
